### ISSUE TITLE
NGBoost via reticulate/RemixAutoML?

### ISSUE THREAD

**Issue by AldridgeCaleb** [AdrianAntico/AutoQuant#40]
Curious about the possible availability of the natural gradient boost algorithm in R? Perhaps via the reticulate package as @AdrianAntico suggested here: https://github.com/stanfordmlgroup/ngboost/issues/14#issuecomment-547145022

**Comment by AdrianAntico** [comment]
@AldridgeCaleb  I want to add this model to the package. The end goal is to have it available for regression, classification, and multiclass (if available, can't recall if it is), along with a CARMA version (my primary reason for wanting to add this model) and hurdle model.

I won't likely be getting to this until January or February as I'm working on adding some other functionalities currently.

**Comment by acca3003** [comment]
I have created a R version of NGBoost.
https://github.com/acca3003/ngboostR
It is a prelimiar version but you can test example.

**Comment by AdrianAntico** [comment]
Thanks for the heads up! Someone opened up an issue for me a while back to incorporate this into RemixAutoML. I'll start looking into incorporating it
