### ISSUE TITLE
non-zero exit status

### ISSUE THREAD

**Issue by jesusarrambide** [AdrianAntico/AutoQuant#81]
I am trying to install the newest version 0.5.0 and get the following:

![image](https://user-images.githubusercontent.com/78067404/221928810-296443bc-8294-402a-b51a-1ab97e4a04ba.png)

Here is my session info:

![image](https://user-images.githubusercontent.com/78067404/221929327-17633d39-47f0-45c2-9e44-dfbc504985f1.png)

**Comment by AdrianAntico** [comment]
@jesusarrambide Thanks for the note. I removed a few experimental functions recently... I updated the vignette and binary .tar file as well. You should be good to go.
