### ISSUE TITLE
Error when calling ModelInsightsReport: object 'RemixOutput' not found

### ISSUE THREAD

**Issue by vincentmgeels** [AdrianAntico/AutoQuant#83]
Hi Adrian,

I attempted to explore the `ModelInsightsReport` function output and have run into the following error after first fitting a model to an example dataset, followed by calling ModelInsightsReport:

```
test.model <- AutoQuant::AutoXGBoostClassifier(
  
  # GPU or CPU
  TreeMethod = "hist",
  NThreads = parallel::detectCores(),
  
  # Metadata args
  OutputSelection = c("Importances", "EvalPlots", "EvalMetrics", "PDFs", "Score_TrainData"),
  model_path = normalizePath("./"),
  metadata_path = NULL,
  ModelID = "tel_dat_model1",
  EncodingMethod = "binary",
  ReturnFactorLevels = TRUE,
  ReturnModelObjects = TRUE,
  SaveModelObjects = FALSE,
  SaveInfoToPDF = TRUE,
  
  # Data args
  data = tel.dat,
  TrainOnFull = FALSE,
  ValidationData = NULL,
  TestData = NULL,
  TargetColumnName = "Loss",
  FeatureColNames = names(tel.dat)[!names(tel.dat) %in%
                                     c("Days", "Vehicle","Loss")],
  WeightsColumnName = NULL,
  IDcols = c("Days", "Vehicle"),
  
  # Model evaluation
  LossFunction = 'binary:logistic',
  CostMatrixWeights = c(1,0,0,1),
  eval_metric = "logloss",
  grid_eval_metric = "MCC",
  NumOfParDepPlots = 3L,
  
  # Grid tuning args
  PassInGrid = NULL,
  GridTune = FALSE,
  BaselineComparison = "default",
  MaxModelsInGrid = 10L,
  MaxRunsWithoutNewWinner = 20L,
  MaxRunMinutes = 24L*60L,
  Verbose = 1L,
  
  # ML args
  Trees = 500L,
  eta = 0.30,
  max_depth = 9L,
  min_child_weight = 1.0,
  subsample = 1,
  colsample_bytree = 1,
  DebugMode = FALSE)



#building an rmarkdown report to view model insights -- run into the following error:
#Quitting from lines 27-38 (Classification_ModelInsights.Rmd) 
#Error in eval(expr, envir, enclos) : object 'RemixOutput' not found
AutoQuant::ModelInsightsReport(
  
  # Meta info
  TargetColumnName = 'Loss',
  PredictionColumnName = 'p1',
  #FeatureColumnNames = Features,
  DateColumnName = NULL,
  
  # Control options
  TargetType = 'classification',
  ModelID = "tel_dat_model1_insights",
  Algo = 'other',
  OutputPath = getwd(),
  ModelObject = test.model)
```

I encounter the following error while ModelInsightsReport attempts to run:
![image](https://user-images.githubusercontent.com/52865270/229834662-0a791319-bde3-498b-ab77-8c42f4358009.png)

Any suggestions you can provide would be greatly appreciated!

**Comment by AdrianAntico** [comment]
@vincentmgeels  Thanks for bringing this up. I've been making some changes to the ML functions so this issue isn't a surprise. I'll be upgrading these reports as well using a new plotting package. This will probably take me a few days to get through the upgrade. I'll send a note over here when they're complete.

**Comment by AdrianAntico** [comment]
@vincentmgeels Upgrades are complete. You'll need to have my AutoPlots package installed, which depends on echarts4r

**Comment by vincentmgeels** [comment]
@AdrianAntico Thanks for following up! I really appreciate it.

**Comment by AdrianAntico** [comment]
@vincentmgeels no problem. Heads up - I just pushed an update. I had the partial dependence line plots spitting out the box plot version. The push I just made fixes that.

**Comment by vincentmgeels** [comment]
Hi @AdrianAntico, I've been running into the following error when trying to install the updated version of AutoQuant:

![image](https://user-images.githubusercontent.com/52865270/233094320-83c40723-1775-4d4b-a8ee-9c7e6a23d4da.png)

For whatever it's worth, I'd already installed the required dependencies listed in the package readme, along with `AutoPlots`, prior to attempting the `AutoQuant` install. Is it possible to upload an updated AutoQuant tar.gz , or is such a file already hosted somewhere? I can install the 1.0.0 tar.gz, but it doesn't include the fixes you described in this thread.

**Comment by AdrianAntico** [comment]
@vincentmgeels I just added the 1.0.1 binary version (tar.gz). Let me know if that helps. I also tried to install from github and was successful. I wonder if it had something to do with the tar.gz file?

**Comment by vincentmgeels** [comment]
Thanks so much for the quick response! I was able to download and install from the updated tar.gz; however, I'm not seeing a different error when calling `ModelInsightsReport`:

```
test.model <- AutoQuant::AutoXGBoostClassifier(
  
  # GPU or CPU
  TreeMethod = "hist",
  NThreads = parallel::detectCores(),
  
  # Metadata args
  OutputSelection = c("Importances", "EvalPlots", "EvalMetrics", "PDFs", "Score_TrainData"),
  model_path = normalizePath("./"),
  metadata_path = NULL,
  ModelID = "tel_dat_model1",
  EncodingMethod = "binary",
  ReturnFactorLevels = TRUE,
  ReturnModelObjects = TRUE,
  SaveModelObjects = FALSE,
  SaveInfoToPDF = TRUE,
  
  # Data args
  data = tel.dat,
  TrainOnFull = FALSE,
  ValidationData = NULL,
  TestData = NULL,
  TargetColumnName = "Loss",
  FeatureColNames = names(tel.dat)[!names(tel.dat) %in%
                                     c("Days", "Vehicle","Loss")],
  WeightsColumnName = NULL,
  IDcols = c("Days", "Vehicle"),
  
  # Model evaluation
  LossFunction = 'binary:logistic',
  CostMatrixWeights = c(1,0,0,1),
  eval_metric = "logloss",
  grid_eval_metric = "MCC",
  NumOfParDepPlots = 3L,
  
  # Grid tuning args
  PassInGrid = NULL,
  GridTune = FALSE,
  BaselineComparison = "default",
  MaxModelsInGrid = 10L,
  MaxRunsWithoutNewWinner = 20L,
  MaxRunMinutes = 24L*60L,
  Verbose = 1L,
  
  # ML args
  Trees = 500L,
  eta = 0.30,
  max_depth = 9L,
  min_child_weight = 1.0,
  subsample = 1,
  colsample_bytree = 1,
  DebugMode = FALSE)

AutoQuant::ModelInsightsReport(
  
  # Meta info
  TargetColumnName = 'Loss',
  PredictionColumnName = 'p1',
  #FeatureColumnNames = Features,
  DateColumnName = NULL,
  
  # Control options
  TargetType = 'classification',
  ModelID = "tel_dat_model1_insights",
  Algo = 'other',
  OutputPath = getwd(),
  ModelObject = test.model)
```

Leads to the error:

![image](https://user-images.githubusercontent.com/52865270/233099087-a0b9ce82-f4ad-4ea1-8749-6b056c880c5b.png)

**Comment by AdrianAntico** [comment]
@vincentmgeels I see the issue. I just made the update and refreshed the binary file. Let me know if that fixes it.

**Comment by vincentmgeels** [comment]
Reinstalled the refreshed binary and now running into a similar (but not exactly the same) error:

![image](https://user-images.githubusercontent.com/52865270/233106932-736dec98-c622-49aa-a556-dba6d7d72375.png)

**Comment by AdrianAntico** [comment]
@vincentmgeels looks like the Width = ... args got overwritten by Height = ... for some reason. I'll go through them and and do a few qa runs. Might take a few hours...

**Comment by vincentmgeels** [comment]
@AdrianAntico I refreshed the main page but the last binary update still appears to be from an hour ago?

**Comment by AdrianAntico** [comment]
@vincentmgeels forgot to push. Should be there now
